#!/usr/bin/env bash
# This script configures the Nginx server and sets up a redirect

# Update and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Modify ownership of the web directory
sudo chown -R "$USER":"$USER" /var/www

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Insert the rewrite rule for redirecting /redirect_me to Google
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me http://www.google.com permanent;" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx

# Optional: Check the syntax of the configuration files
sudo nginx -t
