#!/usr/bin/env bash
# This script installs a load balancer haproxy and configures it

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

# # echo "frontend
# 	    bind *:80
# 	    option forwardfor  
#         default_backend nginx_webservers

# backend nginx_webservers
#         balance roundrobin
#         server 446418-web-01 34.224.6.65:80 check
#         server 446418-web-02 52.91.148.2:80 check
# " | sudo tee -a /etc/haproxy/haproxy.cfg
#echo "ENABLED=1" > /etc/default/haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 446418-web-01 34.244.6.65:80 check\n\tserver 446418-web-02 52.91.148.2:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart
